function a(k){var g=0;return function(){return g<k.length?{done:!1,value:k[g++]}:{done:!0}}}function n(k){var g="undefined"!=typeof Symbol&&Symbol.iterator&&k[Symbol.iterator];return g?g.call(k):{next:a(k)}}function v(k){if(!(k instanceof Array)){k=n(k);for(var g,d=[];!(g=k.next()).done;)d.push(g.value);k=d}return k}var A="User-defined Type Import Function Table Memory Global Export Start Element Code Data".split(" "),E=[];E[127]="i32";E[126]="i64";E[125]="f32";E[124]="f64";E[112]="anyFunc";
E[96]="func";E[64]="void";
var H=["Function","Table","Memory","Global"],O=[["unreachable"],["nop"],["block",I],["loop",I],["if",I],["else"],,,,,,["end"],["br",I],["br_if",I],["br_table",J],["return"],["call",K],["call_indirect",I,I],,,,,,,,,["drop"],["select"],,,,,["get_local",I],["set_local",I],["tee_local",I],["get_global",I],["set_global",I],,,,["i32.load",I,I],["i64.load",I,I],["f32.load",I,I],["f64.load",I,I],["i32.load8_s",I,I],["i32.load8_u",I,I],["i32.load16_s",I,I],["i32.load16_u",I,I],["i64.load8_s",I,I],["i64.load8_u",
I,I],["i64.load16_s",I,I],["i64.load16_u",I,I],["i64.load32_s",I,I],["i64.load32_u",I,I],["i32.store",I,I],["i64.store",I,I],["f32.store",I,I],["f64.store",I,I],["i32.store8",I,I],["i32.store16",I,I],["i64.store8",I,I],["i64.store16",I,I],["i64.store32",I,I],["memory.size",I],["memory.grow",I],["i32.const",L],["i64.const",L],["f32.const",M],["f64.const",N],["i32.eqz"],["i32.eq"],["i32.ne"],["i32.lt_s"],["i32.lt_u"],["i32.gt_s"],["i32.gt_u"],["i32.le_s"],["i32.le_u"],["i32.ge_s"],["i32.ge_u"],["i64.eqz"],
["i64.eq"],["i64.ne"],["i64.lt_s"],["i64.lt_u"],["i64.gt_s"],["i64.gt_u"],["i64.le_s"],["i64.le_u"],["i64.ge_s"],["i64.ge_u"],["f32.eq"],["f32.ne"],["f32.lt"],["f32.gt"],["f32.le"],["f32.ge"],["f64.eq"],["f64.ne"],["f64.lt"],["f64.gt"],["f64.le"],["f64.ge"],["i32.clz"],["i32.ctz"],["i32.popcnt"],["i32.add"],["i32.sub"],["i32.mul"],["i32.div_s"],["i32.div_u"],["i32.rem_s"],["i32.rem_u"],["i32.and"],["i32.or"],["i32.xor"],["i32.shl"],["i32.shr_s"],["i32.shr_u"],["i32.rotl"],["i32.rotr"],["i64.clz"],
["i64.ctz"],["i64.popcnt"],["i64.add"],["i64.sub"],["i64.mul"],["i64.div_s"],["i64.div_u"],["i64.rem_s"],["i64.rem_u"],["i64.and"],["i64.or"],["i64.xor"],["i64.shl"],["i64.shr_s"],["i64.shr_u"],["i64.rotl"],["i64.rotr"],["f32.abs"],["f32.neg"],["f32.ceil"],["f32.floor"],["f32.trunc"],["f32.nearest"],["f32.sqrt"],["f32.add"],["f32.sub"],["f32.mul"],["f32.div"],["f32.min"],["f32.max"],["f32.copysign"],["f64.abs"],["f64.neg"],["f64.ceil"],["f64.floor"],["f64.trunc"],["f64.nearest"],["f64.sqrt"],["f64.add"],
["f64.sub"],["f64.mul"],["f64.div"],["f64.min"],["f64.max"],["f64.copysign"],["i32.wrap/i64"],["i32.trunc_s/f32"],["i32.trunc_u/f32"],["i32.trunc_s/f64"],["i32.trunc_u/f64"],["i64.extend_s/i32"],["i64.extend_u/i32"],["i64.trunc_s/f32"],["i64.trunc_u/f32"],["i64.trunc_s/f64"],["i64.trunc_u/f64"],["f32.convert_s/i32"],["f32.convert_u/i32"],["f32.convert_s/i64"],["f32.convert_u/i64"],["f32.demote/f64"],["f64.convert_s/i32"],["f64.convert_u/i32"],["f64.convert_s/i64"],["f64.convert_u/i64"],["f64.promote/f32"],
["i32.reinterpret/f32"],["i64.reinterpret/f64"],["f32.reinterpret/i32"],["f64.reinterpret/i64"]];function L(k,g){var d=0,h=0,m=0;do{var c=k[g+m];++m;d|=(c&127)<<h;h+=7}while(0!=(c&128));32>h&&c&64&&(d|=-1<<h);return[d,m]}function I(k,g){for(var d=0,h=0,m=0;;){var c=k[g+m];d|=(c&127)<<h;++m;if(0==(c&128))break;h+=7}return[d,m]}
function J(k,g){var d=[],h=n(I(k,g)),m=h.next().value,c=h.next().value;h=m;g+=c;d.push(m,c);for(var D=0;D<h;++D)c=n(I(k,g)),m=c.next().value,c=c.next().value,g+=c,d.push(m,c);d.push.apply(d,v(I(k,g)));return d}var P=[];function K(k,g){var d=n(I(k,g)),h=d.next().value;d=["",d.next().value];d[0]=h<P.length?P[h]:String(h);return d}function Q(k){return String.fromCharCode.apply(String,k)}function M(k,g){return[(new Float32Array(k.slice(g,g+4).buffer))[0],4]}
function N(k,g){return[(new Float64Array(k.slice(g,g+8).buffer))[0],8]}
export default function(k,g){function d(p,r){r=void 0===r?"":r;do{var t=Math.min(g,p),q=Array.from(c.subarray(b,b+t)).map(function(y){return y.toString(16).padStart(2,"0")}).join(" ").padEnd(3*g);B+=q+" @"+b.toString().padStart(D,"0")+": "+r+"\n";b+=t;p-=t;r=""}while(0<p)}function h(p,r){p=void 0===p?"":p;r=void 0===r?"":r;var t=n(I(c,b)),q=t.next().value;t=t.next().value;d(t,p+q+r);return q}function m(){var p=O[c[b]],r=p[0],t=1;p=n(p.slice(1));for(var q=p.next();!q.done;q=p.next()){q=q.value;
q=q(c,b+t);for(var y=0;y<q.length;y+=2)r+=" "+q[y],t+=q[y+1]}d(t,r)}g=void 0===g?16:g;var c=new Uint8Array(k),D=Math.ceil(Math.log2(c.length)/Math.log2(10)),b=0,B="";d(4,'Wasm magic number: "\\0asm"');d(4,"Wasm version: 1");var G=[];for(P.length=0;b<c.length;){B+="\n\n\n";var C=c[b];d(1,"section: "+A[C]+" ("+C+")");var z=h("size: "," bytes");z=b+z;for(0!==C&&h(8===C?"entry point: func ":"count: ");b<z;)switch(C){case 0:var e=n(I(c,b)),f=e.next().value;e=e.next().value;var l=Q(c.slice(b+e,b+e+f)).replace(/\n/g,
"\\n").replace(/\0/g,"\\0");for(d(f+e,'name: "'+l+'"');b<z;)f=Math.min(g,z-b),e=Q(c.slice(b,b+f)).replace(/[^ -~]/g,"."),d(f,e);break;case 1:f=1;e="";l=n(["func (",") -> ("]);for(var w=l.next();!w.done;w=l.next()){w=w.value;var x=n(I(c,b+f)),u=x.next().value;x=x.next().value;f+=x;e+=w;e+=Array.from(c.slice(b+f,b+f+u)).map(function(p){return E[p&127]}).join(" ");f+=u}e+=")";G.push(e);d(f,e);break;case 2:B+="\n";f=[];e=n(["module:","field: "]);for(l=e.next();!l.done;l=e.next())l=l.value,u=n(I(c,b)),
w=u.next().value,u=u.next().value,x=Q(c.slice(b+u,b+u+w)).replace(/\n/g,"\\n").replace(/\0/g,"\\0"),f.push(x),d(w+u,l+' "'+x+'"');e=c[b];2===e?(d(1,"external memory"),f=c[b],d(1,f?"limit":"no limit"),h("initial pages: "),f&&h("max allocation: "," pages")):0===e&&(l=n(I(c,b+1)),e=l.next().value,l=l.next().value,d(l+1,"external "+G[e]),P.push(f.join(".")));break;case 3:e=n(I(c,b));f=e.next().value;e=e.next().value;d(e,G[f]);break;case 4:d(1,"element type: "+E[c[b]]);f=c[b];d(1,f?"limit":"no limit");
h("initial count: ");f&&h("maximum: ");break;case 5:f=c[b];d(1,f?"limit":"no limit");h("initial pages: ");f&&h("max allocation: "," pages");break;case 6:d(1,E[c[b]]);d(1,c[b]?"mutable":"immutable");m();m();break;case 7:e=n(I(c,b));f=e.next().value;e=e.next().value;l=Q(c.slice(b+e,b+e+f)).replace(/\n/g,"\\n").replace(/\0/g,"\\0");d(f+e,'field: "'+l+'"');d(1,"type: "+H[c[b]]);h("index: ");break;case 9:h("table index: ");m();m();f=h("element count: ");for(e=0;e<f;++e)h("function index: ");break;case 10:B+=
"\n";f=h("func body size: "," bytes");f=b+f;l=n(I(c,b));e=l.next().value;l=l.next().value;w="local vars:";for(u=0;u<e;++u){var F=n(I(c,b+l));x=F.next().value;F=F.next().value;l+=F;w+=(" "+E[c[b+l]]).repeat(x);++l}for(d(l,w);b<f;)m();break;case 11:h("linear memory index: ");m();m();f=h("size of data: "," bytes");for(f=b+f;b<f;)e=Math.min(g,f-b),l=Q(c.slice(b,b+e)).replace(/[^ -~]/g,"."),d(e,l);break;default:d(1)}b=z}return B};