function a(k){var g=0;return function(){return g<k.length?{done:!1,value:k[g++]}:{done:!0}}}function n(k){var g="undefined"!=typeof Symbol&&Symbol.iterator&&k[Symbol.iterator];return g?g.call(k):{next:a(k)}}function u(k){if(!(k instanceof Array)){k=n(k);for(var g,d=[];!(g=k.next()).done;)d.push(g.value);k=d}return k}var A="User-defined Type Import Function Table Memory Global Export Start Element Code Data".split(" "),E=[];E[127]="i32";E[126]="i64";E[125]="f32";E[124]="f64";E[112]="anyFunc";
E[96]="func";E[64]="void";
var I=["Function","Table","Memory","Global"],P=[["unreachable"],["nop"],["block",J],["loop",J],["if",J],["else"],,,,,,["end"],["br",J],["br_if",J],["br_table",K],["return"],["call",L],["call_indirect",J,J],,,,,,,,,["drop"],["select"],,,,,["get_local",J],["set_local",J],["tee_local",J],["get_global",J],["set_global",J],,,,["i32.load",J,J],["i64.load",J,J],["f32.load",J,J],["f64.load",J,J],["i32.load8_s",J,J],["i32.load8_u",J,J],["i32.load16_s",J,J],["i32.load16_u",J,J],["i64.load8_s",J,J],["i64.load8_u",
J,J],["i64.load16_s",J,J],["i64.load16_u",J,J],["i64.load32_s",J,J],["i64.load32_u",J,J],["i32.store",J,J],["i64.store",J,J],["f32.store",J,J],["f64.store",J,J],["i32.store8",J,J],["i32.store16",J,J],["i64.store8",J,J],["i64.store16",J,J],["i64.store32",J,J],["memory.size",J],["memory.grow",J],["i32.const",M],["i64.const",M],["f32.const",N],["f64.const",O],["i32.eqz"],["i32.eq"],["i32.ne"],["i32.lt_s"],["i32.lt_u"],["i32.gt_s"],["i32.gt_u"],["i32.le_s"],["i32.le_u"],["i32.ge_s"],["i32.ge_u"],["i64.eqz"],
["i64.eq"],["i64.ne"],["i64.lt_s"],["i64.lt_u"],["i64.gt_s"],["i64.gt_u"],["i64.le_s"],["i64.le_u"],["i64.ge_s"],["i64.ge_u"],["f32.eq"],["f32.ne"],["f32.lt"],["f32.gt"],["f32.le"],["f32.ge"],["f64.eq"],["f64.ne"],["f64.lt"],["f64.gt"],["f64.le"],["f64.ge"],["i32.clz"],["i32.ctz"],["i32.popcnt"],["i32.add"],["i32.sub"],["i32.mul"],["i32.div_s"],["i32.div_u"],["i32.rem_s"],["i32.rem_u"],["i32.and"],["i32.or"],["i32.xor"],["i32.shl"],["i32.shr_s"],["i32.shr_u"],["i32.rotl"],["i32.rotr"],["i64.clz"],
["i64.ctz"],["i64.popcnt"],["i64.add"],["i64.sub"],["i64.mul"],["i64.div_s"],["i64.div_u"],["i64.rem_s"],["i64.rem_u"],["i64.and"],["i64.or"],["i64.xor"],["i64.shl"],["i64.shr_s"],["i64.shr_u"],["i64.rotl"],["i64.rotr"],["f32.abs"],["f32.neg"],["f32.ceil"],["f32.floor"],["f32.trunc"],["f32.nearest"],["f32.sqrt"],["f32.add"],["f32.sub"],["f32.mul"],["f32.div"],["f32.min"],["f32.max"],["f32.copysign"],["f64.abs"],["f64.neg"],["f64.ceil"],["f64.floor"],["f64.trunc"],["f64.nearest"],["f64.sqrt"],["f64.add"],
["f64.sub"],["f64.mul"],["f64.div"],["f64.min"],["f64.max"],["f64.copysign"],["i32.wrap/i64"],["i32.trunc_s/f32"],["i32.trunc_u/f32"],["i32.trunc_s/f64"],["i32.trunc_u/f64"],["i64.extend_s/i32"],["i64.extend_u/i32"],["i64.trunc_s/f32"],["i64.trunc_u/f32"],["i64.trunc_s/f64"],["i64.trunc_u/f64"],["f32.convert_s/i32"],["f32.convert_u/i32"],["f32.convert_s/i64"],["f32.convert_u/i64"],["f32.demote/f64"],["f64.convert_s/i32"],["f64.convert_u/i32"],["f64.convert_s/i64"],["f64.convert_u/i64"],["f64.promote/f32"],
["i32.reinterpret/f32"],["i64.reinterpret/f64"],["f32.reinterpret/i32"],["f64.reinterpret/i64"]];function M(k,g){var d=0,h=0,m=0;do{var c=k[g+m];++m;d|=(c&127)<<h;h+=7}while(0!=(c&128));32>h&&c&64&&(d|=-1<<h);return[d,m]}function J(k,g){for(var d=0,h=0,m=0;;){var c=k[g+m];d|=(c&127)<<h;++m;if(0==(c&128))break;h+=7}return[d,m]}
function K(k,g){var d=[],h=n(J(k,g)),m=h.next().value,c=h.next().value;h=m;g+=c;d.push(m,c);for(var D=0;D<h;++D)c=n(J(k,g)),m=c.next().value,c=c.next().value,g+=c,d.push(m,c);d.push.apply(d,u(J(k,g)));return d}var Q=[];function L(k,g){var d=n(J(k,g)),h=d.next().value;d=["",d.next().value];d[0]=h<Q.length?Q[h]:String(h);return d}function R(k){return String.fromCharCode.apply(String,k)}function N(k,g){return[(new Float32Array(k.slice(g,g+4).buffer))[0],4]}
function O(k,g){return[(new Float64Array(k.slice(g,g+8).buffer))[0],8]}
export default function(k,g){function d(p,r){r=void 0===r?"":r;var fail=99;do{var q=Math.min(g,p),y=Array.from(c.subarray(b,b+q)).map(function(v){return v.toString(16).padStart(2,"0")}).join(" ").padEnd(3*g);B+=y+" @"+b.toString().padStart(D,"0")+": "+r+"\n";b+=q;p-=q;r=""}while(0<p&&--fail)}function h(p,r){p=void 0===p?"":p;r=void 0===r?"":r;var q=n(J(c,b)),y=q.next().value;q=q.next().value;d(q,p+y+r);return y}function m(p){var r=c[b],q=P[r];if(void 0===q)return d(1,"Unrecognized opcode"),b=p||c.length,11;p=q[0];
var y=1;q=n(q.slice(1));for(var v=q.next();!v.done;v=q.next()){v=v.value;v=v(c,b+y);for(var F=0;F<v.length;F+=2)p+=" "+v[F],y+=v[F+1]}d(y,p);return r}g=void 0===g?16:g;var c=new Uint8Array(k),D=Math.ceil(Math.log2(c.length)/Math.log2(10)),b=0,B="";d(4,'Wasm magic number: "\\0asm"');d(4,"Wasm version: 1");var H=[];for(Q.length=0;b<c.length;){B+="\n\n\n";var C=c[b];d(1,"section: "+A[C]+" ("+C+")");var z=h("size: "," bytes");z=b+z;for(0!==C&&h(8===C?"entry point: func ":"count: ");b<z;)switch(C){case 0:var e=
n(J(c,b)),f=e.next().value;e=e.next().value;var l=R(c.slice(b+e,b+e+f)).replace(/\n/g,"\\n").replace(/\0/g,"\\0");for(d(f+e,'name: "'+l+'"');b<z;)f=Math.min(g,z-b),e=R(c.slice(b,b+f)).replace(/[^ -~]/g,"."),d(f,e);break;case 1:f=1;e="";l=n(["func (",") -> ("]);for(var w=l.next();!w.done;w=l.next()){w=w.value;var x=n(J(c,b+f)),t=x.next().value;x=x.next().value;f+=x;e+=w;e+=Array.from(c.slice(b+f,b+f+t)).map(function(p){return E[p&127]}).join(" ");f+=t}e+=")";H.push(e);d(f,e);break;case 2:B+="\n";f=
[];e=n(["module:","field: "]);for(l=e.next();!l.done;l=e.next())l=l.value,t=n(J(c,b)),w=t.next().value,t=t.next().value,x=R(c.slice(b+t,b+t+w)).replace(/\n/g,"\\n").replace(/\0/g,"\\0"),f.push(x),d(w+t,l+' "'+x+'"');e=c[b];2===e?(d(1,"external memory"),f=c[b],d(1,f?"limit":"no limit"),h("initial pages: "),f&&h("max allocation: "," pages")):0===e&&(l=n(J(c,b+1)),e=l.next().value,l=l.next().value,d(l+1,"external "+H[e]),Q.push(f.join(".")));break;case 3:e=n(J(c,b));f=e.next().value;e=e.next().value;
d(e,H[f]);break;case 4:d(1,"element type: "+E[c[b]]);f=c[b];d(1,f?"limit":"no limit");h("initial count: ");f&&h("maximum: ");break;case 5:f=c[b];d(1,f?"limit":"no limit");h("initial pages: ");f&&h("max allocation: "," pages");break;case 6:d(1,E[c[b]]);for(d(1,c[b]?"mutable":"immutable");11!==m(););break;case 7:e=n(J(c,b));f=e.next().value;e=e.next().value;l=R(c.slice(b+e,b+e+f)).replace(/\n/g,"\\n").replace(/\0/g,"\\0");d(f+e,'field: "'+l+'"');d(1,"type: "+I[c[b]]);h("index: ");break;case 9:for(h("table index: ");11!==
m(););f=h("element count: ");for(e=0;e<f;++e)h("function index: ");break;case 10:B+="\n";f=h("func body size: "," bytes");f=b+f;l=n(J(c,b));e=l.next().value;l=l.next().value;w="local vars:";for(t=0;t<e;++t){var G=n(J(c,b+l));x=G.next().value;G=G.next().value;l+=G;w+=(" "+E[c[b+l]]).repeat(x);++l}for(d(l,w);b<f;)m(f);b=f;break;case 11:for(h("linear memory index: ");11!==m(););f=h("size of data: "," bytes");for(f=b+f;b<f;)e=Math.min(g,f-b),l=R(c.slice(b,b+e)).replace(/[^ -~]/g," ").trimEnd(),d(e,l);
break;default:d(1)}b=z}return B};