function a(f){var h=0;return function(){return h<f.length?{done:!1,value:f[h++]}:{done:!0}}}function n(f){var h="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return h?h.call(f):{next:a(f)}}function q(f){if(!(f instanceof Array)){f=n(f);for(var h,g=[];!(h=f.next()).done;)g.push(h.value);f=g}return f}var v="User-defined Type Import Function Table Memory Global Export Start Element Code Data".split(" "),A=[];A[127]="i32";A[126]="i64";A[125]="f32";A[124]="f64";A[112]="anyFunc";
A[96]="func";A[64]="void";
var B=["Function","Table","Memory","Global"],H=[["unreachable"],["nop"],["block",C],["loop",C],["if",C],["else"],,,,,,["end"],["br",C],["br_if",C],["br_table",D],["return"],["call",C],["call_indirect",C,C],,,,,,,,,["drop"],["select"],,,,,["get_local",C],["set_local",C],["tee_local",C],["get_global",C],["set_global",C],,,,["i32.load",C,C],["i64.load",C,C],["f32.load",C,C],["f64.load",C,C],["i32.load8_s",C,C],["i32.load8_u",C,C],["i32.load16_s",C,C],["i32.load16_u",C,C],["i64.load8_s",C,C],["i64.load8_u",
C,C],["i64.load16_s",C,C],["i64.load16_u",C,C],["i64.load32_s",C,C],["i64.load32_u",C,C],["i32.store",C,C],["i64.store",C,C],["f32.store",C,C],["f64.store",C,C],["i32.store8",C,C],["i32.store16",C,C],["i64.store8",C,C],["i64.store16",C,C],["i64.store32",C,C],["memory.size",C],["memory.grow",C],["i32.const",E],["i64.const",E],["f32.const",F],["f64.const",G],["i32.eqz"],["i32.eq"],["i32.ne"],["i32.lt_s"],["i32.lt_u"],["i32.gt_s"],["i32.gt_u"],["i32.le_s"],["i32.le_u"],["i32.ge_s"],["i32.ge_u"],["i64.eqz"],
["i64.eq"],["i64.ne"],["i64.lt_s"],["i64.lt_u"],["i64.gt_s"],["i64.gt_u"],["i64.le_s"],["i64.le_u"],["i64.ge_s"],["i64.ge_u"],["f32.eq"],["f32.ne"],["f32.lt"],["f32.gt"],["f32.le"],["f32.ge"],["f64.eq"],["f64.ne"],["f64.lt"],["f64.gt"],["f64.le"],["f64.ge"],["i32.clz"],["i32.ctz"],["i32.popcnt"],["i32.add"],["i32.sub"],["i32.mul"],["i32.div_s"],["i32.div_u"],["i32.rem_s"],["i32.rem_u"],["i32.and"],["i32.or"],["i32.xor"],["i32.shl"],["i32.shr_s"],["i32.shr_u"],["i32.rotl"],["i32.rotr"],["i64.clz"],
["i64.ctz"],["i64.popcnt"],["i64.add"],["i64.sub"],["i64.mul"],["i64.div_s"],["i64.div_u"],["i64.rem_s"],["i64.rem_u"],["i64.and"],["i64.or"],["i64.xor"],["i64.shl"],["i64.shr_s"],["i64.shr_u"],["i64.rotl"],["i64.rotr"],["f32.abs"],["f32.neg"],["f32.ceil"],["f32.floor"],["f32.trunc"],["f32.nearest"],["f32.sqrt"],["f32.add"],["f32.sub"],["f32.mul"],["f32.div"],["f32.min"],["f32.max"],["f32.copysign"],["f64.abs"],["f64.neg"],["f64.ceil"],["f64.floor"],["f64.trunc"],["f64.nearest"],["f64.sqrt"],["f64.add"],
["f64.sub"],["f64.mul"],["f64.div"],["f64.min"],["f64.max"],["f64.copysign"],["i32.wrap/i64"],["i32.trunc_s/f32"],["i32.trunc_u/f32"],["i32.trunc_s/f64"],["i32.trunc_u/f64"],["i64.extend_s/i32"],["i64.extend_u/i32"],["i64.trunc_s/f32"],["i64.trunc_u/f32"],["i64.trunc_s/f64"],["i64.trunc_u/f64"],["f32.convert_s/i32"],["f32.convert_u/i32"],["f32.convert_s/i64"],["f32.convert_u/i64"],["f32.demote/f64"],["f64.convert_s/i32"],["f64.convert_u/i32"],["f64.convert_s/i64"],["f64.convert_u/i64"],["f64.promote/f32"],
["i32.reinterpret/f32"],["i64.reinterpret/f64"],["f32.reinterpret/i32"],["f64.reinterpret/i64"]];function E(f,h){var g=0,k=0,m=0;do{var e=f[h+m];++m;g|=(e&127)<<k;k+=7}while(0!=(e&128));32>k&&e&64&&(g|=-1<<k);return[g,m]}function C(f,h){for(var g=0,k=0,m=0;;){var e=f[h+m];g|=(e&127)<<k;++m;if(0==(e&128))break;k+=7}return[g,m]}
function D(f,h){var g=[],k=n(C(f,h)),m=k.next().value,e=k.next().value;h+=e;g.push(m,e);for(k=0;k<m;++k)e=n(C(f,h)),m=e.next().value,e=e.next().value,h+=e,g.push(m,e);g.push.apply(g,q(C(f,h)));return g}function I(f){return String.fromCharCode.apply(String,f)}function F(f,h){return[(new Float32Array(f.slice(h,h+4).buffer))[0],4]}function G(f,h){return[(new Float64Array(f.slice(h,h+8).buffer))[0],8]}
window.getDisassembly=function(f,h){function g(c,b){b=void 0===b?"":b;do{var g=Math.min(h,c),f=Array.from(e.subarray(d,d+g)).map(function(d){return d.toString(16).padStart(2,"0")}).join(" ").padEnd(3*h);w+=f+" @"+d.toString().padStart(J,"0")+": "+b+"\n";d+=g;c-=g;b=""}while(0<c)}function k(b,c){b=void 0===b?"":b;c=void 0===c?"":c;var h=n(C(e,d)),f=h.next().value;h=h.next().value;g(h,b+f+c);return f}function m(){var b=H[e[d]],c=b[0],h=1;b=n(b.slice(1));for(var f=b.next();!f.done;f=b.next()){f=f.value;
f=f(e,d+h);for(var k=0;k<f.length;k+=2)c+=" "+f[k],h+=f[k+1]}g(h,c)}h=void 0===h?16:h;var e=new Uint8Array(f),J=Math.ceil(Math.log2(e.length)/Math.log2(10)),d=0,w="";g(4,'Wasm magic number: "\\0asm"');g(4,"Wasm version: 1");for(var z=[];d<e.length;){w+="\n\n\n";var x=e[d];g(1,"section: "+v[x]+" ("+x+")");var t=k("size: "," bytes");t=d+t;for(0!==x&&k(8===x?"entry point: func ":"count: ");d<t;)switch(x){case 0:var b=n(C(e,d)),c=b.next().value;b=b.next().value;var l=I(e.slice(d+b,d+b+c)).replace(/\n/g,
"\\n").replace(/\0/g,"\\0");for(g(c+b,'name: "'+l+'"');d<t;)c=Math.min(h,t-d),b=I(e.slice(d,d+c)).replace(/[^ -~]/g,"."),g(c,b);break;case 1:if(96===e[d]){c=1;b="";l=n(["func (",") -> ("]);for(var p=l.next();!p.done;p=l.next()){p=p.value;var u=n(C(e,d+c)),r=u.next().value;u=u.next().value;c+=u;b+=p;b+=Array.from(e.slice(d+c,d+c+r)).map(function(b){return A[b&127]}).join(" ");c+=r}b+=")";z.push(b);g(c,b)}else throw"unrecognized Wasm type "+A[type]||type;break;case 2:w+="\n";c=n(["module: ","field:  "]);
for(b=c.next();!b.done;b=c.next())b=b.value,p=n(C(e,d)),l=p.next().value,p=p.next().value,r=I(e.slice(d+p,d+p+l)).replace(/\n/g,"\\n").replace(/\0/g,"\\0"),g(l+p,b+' "'+r+'"');c=e[d];2===c?(g(1,"external memory"),c=e[d],g(1,c?"limit":"no limit"),k("initial pages: "),c&&k("max allocation: "," pages")):0===c&&(b=n(C(e,d+1)),c=b.next().value,b=b.next().value,g(b+1,"external "+z[c]));break;case 3:b=n(C(e,d));c=b.next().value;b=b.next().value;g(b,z[c]);break;case 4:g(1,"element type: "+A[e[d]]);c=e[d];
g(1,c?"limit":"no limit");k("initial count: ");c&&k("maximum: ");break;case 5:c=e[d];g(1,c?"limit":"no limit");k("initial pages: ");c&&k("max allocation: "," pages");break;case 6:g(1,A[e[d]]);g(1,e[d]?"mutable":"immutable");m();m();break;case 7:b=n(C(e,d));c=b.next().value;b=b.next().value;l=I(e.slice(d+b,d+b+c)).replace(/\n/g,"\\n").replace(/\0/g,"\\0");g(c+b,'field: "'+l+'"');g(1,"type: "+B[e[d]]);k("index: ");break;case 10:w+="\n";c=k("func body size: "," bytes");c=d+c;l=n(C(e,d));b=l.next().value;
l=l.next().value;p="local vars:";for(r=0;r<b;++r){var y=n(C(e,d+l));u=y.next().value;y=y.next().value;l+=y;p+=(" "+A[e[d+l]]).repeat(u);++l}for(g(l,p);d<c;)m();break;case 11:k("linear memory index: ");m();m();c=k("size of data: "," bytes");for(c=d+c;d<c;)b=Math.min(h,c-d),l=I(e.slice(d,d+b)).replace(/[^ -~]/g,"."),g(b,l);break;default:g(1)}d=t}return w};